# Unit 12 - Tales from the Crypto

---

## 1. Sentiment Analysis

Use the [newsapi](https://newsapi.org/) to pull the latest news articles for Bitcoin and Ethereum and create a DataFrame of sentiment scores for each coin.

Use descriptive statistics to answer the following questions:
1. Which coin had the highest mean positive score?
2. Which coin had the highest negative score?
3. Which coin had the highest positive score?

In [41]:
# Initial imports
import os
import pandas as pd
from dotenv import load_dotenv
import nltk as nltk
from nltk.corpus import stopwords
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
from newsapi import NewsApiClient

%matplotlib inline

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\mattr\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [42]:
# Read your api key environment variable
load_dotenv()
key = os.getenv('NEWSAPI')


# YOUR CODE HERE!

In [43]:
# Create a newsapi client
news = NewsApiClient(api_key=key)
# YOUR CODE HERE!

In [44]:
# Fetch the Bitcoin news articles
articles_btc = news.get_everything(q='Bitcoin', language='en')
# YOUR CODE HERE!

In [45]:
# Fetch the Ethereum news articles
articles_eth = news.get_everything(q='Ethereum', language='en')
# articles_eth
# YOUR CODE HERE!

In [46]:
# Create the Bitcoin sentiment scores DataFrame
btc_sentiments = []
for article in articles_btc["articles"]:
    try:
        text = article["content"]
        date = article["publishedAt"][:10]
        sentiment = analyzer.polarity_scores(text)
        compound = sentiment["compound"]
        pos = sentiment["pos"]
        neu = sentiment["neu"]
        neg = sentiment["neg"]
        
        btc_sentiments.append({
            "text": text,
            "date": date,
            "compound": compound,
            "positive": pos,
            "negative": neg,
            "neutral": neu
            
        })
        
    except AttributeError:
        pass

btc_df = pd.DataFrame(btc_sentiments)
btc_df
# YOUR CODE HERE!

,text,date,compound,positive,negative,neutral
0,"When Russia invaded Ukraine, Niki Proshin was ...",2022-03-17,0.0000,0.000,0.000,1.000
1,"""Bitcoin was seen by many of its libertarian-l...",2022-03-12,-0.7713,0.000,0.169,0.831
2,Feb 22 (Reuters) - Bitcoin miners are feeling ...,2022-02-22,-0.1779,0.046,0.067,0.887
3,March 1 (Reuters) - Bitcoin has leapt since Ru...,2022-03-01,0.0000,0.000,0.000,1.000
4,Whose side is cryptocurrency on? If you had as...,2022-03-08,-0.3182,0.055,0.091,0.854
5,Getty\r\nWelcome to Nonfungible Tidbits. Our f...,2022-03-05,-0.6808,0.074,0.187,0.739
6,Here's what happened this week in the crypto w...,2022-03-19,0.4588,0.081,0.000,0.919
7,An appeals court decided shilling for an unreg...,2022-02-19,0.3400,0.066,0.000,0.934
8,Nurphoto/Getty\r\nAs Russia launched an invasi...,2022-02-28,0.1280,0.048,0.000,0.952
9,"LONDON, March 4 (Reuters) - Cryptocurrencies h...",2022-03-04,-0.1280,0.000,0.046,0.954
10,March 15 (Reuters) - Bitcoin loves flirting wi...,2022-03-15,0.3182,0.098,0.038,0.864
11,Feb 24 - Welcome to the home for real-time cov...,2022-02-24,0.6369,0.152,0.000,0.848
12,<ul><li>\r\nSummary</li><li>\r\nLaw firms</li>...,2022-03-10,0.4215,0.091,0.000,0.909
13,The Ukrainian government asking for donations ...,2022-03-01,0.5574,0.104,0.000,0.896
14,"SAN SALVADOR, March 11 (Reuters) - El Salvador...",2022-03-11,0.0000,0.000,0.000,1.000
15,Bitcoin rallied to a two-week high on Tuesday ...,2022-03-01,-0.4588,0.069,0.141,0.789
16,"SAN SALVADOR, Feb 20 (Reuters) - El Salvador P...",2022-02-20,0.3612,0.070,0.000,0.930
17,Motherboard found old footage from one of the ...,2022-03-16,0.0000,0.000,0.000,1.000
18,SEC officials do not know the whereabouts of S...,2022-03-02,-0.2023,0.000,0.053,0.947
19,Illustration by James Bareham / The Verge\r\n\...,2022-02-26,-0.4588,0.000,0.083,0.917

In [47]:
# Create the Ethereum sentiment scores DataFrame
# YOUR CODE HERE!
eth_sentiments = []
for article in articles_eth["articles"]:
    try:
        text = article["content"]
        date = article["publishedAt"][:10]
        sentiment = analyzer.polarity_scores(text)
        compound = sentiment["compound"]
        pos = sentiment["pos"]
        neu = sentiment["neu"]
        neg = sentiment["neg"]
        
        eth_sentiments.append({
            "text": text,
            "date": date,
            "compound": compound,
            "positive": pos,
            "negative": neg,
            "neutral": neu
            
        })
        
    except AttributeError:
        pass
eth_df = pd.DataFrame(eth_sentiments)
eth_df

,text,date,compound,positive,negative,neutral
0,"In February, shit hit the fan in the usual way...",2022-03-01,-0.3182,0.059,0.093,0.848
1,Coinbase reported that the share of trading vo...,2022-02-25,0.6705,0.188,0.000,0.812
2,Illustration by James Bareham / The Verge\r\n\...,2022-02-26,-0.4588,0.000,0.083,0.917
3,"If it sounds too good to be true, youre not wr...",2022-03-13,0.8340,0.236,0.050,0.713
4,"It seems that in 2022, you cant escape from th...",2022-03-03,-0.1326,0.000,0.044,0.956
5,The cryptocurrency boom over the past few year...,2022-03-02,0.0000,0.000,0.000,1.000
6,A version of this article was published in TIM...,2022-02-24,0.0000,0.000,0.000,1.000
7,Joe Biden is dipping his toes into crypto. On ...,2022-03-09,0.5267,0.108,0.000,0.892
8,The cryptocurrency boom over the past few year...,2022-03-16,0.0000,0.000,0.000,1.000
9,The cryptocurrency boom over the past few year...,2022-03-09,0.0000,0.000,0.000,1.000
10,If blockchain technology is to reach true mass...,2022-03-07,0.7722,0.249,0.059,0.692
11,The news: Blockchain specialist ConsenSys scoo...,2022-03-17,0.4019,0.078,0.000,0.922
12,(Kitco News) The escalating Russia-Ukraine cri...,2022-03-01,-0.5267,0.047,0.115,0.838
13,During the days leading up to the March 11 pur...,2022-03-17,0.5106,0.088,0.000,0.912
14,Personal Finance Insider writes about products...,2022-03-04,0.5346,0.158,0.000,0.842
15,The travel services industry and fast-food cha...,2022-03-15,0.4588,0.091,0.000,0.909
16,A Ukrainian nonprofit has raised bitcoin worth...,2022-02-25,0.4939,0.199,0.083,0.718
17,As the international community rallies around ...,2022-03-03,0.0000,0.000,0.000,1.000
18,Inflation rates have expectedly begun to soar ...,2022-03-14,0.0516,0.074,0.068,0.858
19,"Representations of cryptocurrencies Bitcoin, E...",2022-03-02,0.0000,0.000,0.000,1.000

In [48]:
# Describe the Bitcoin Sentiment

# YOUR CODE HERE!
btc_df.describe()

        compound   positive   negative    neutral
count  20.000000  20.000000  20.000000  20.000000
mean    0.001295   0.047700   0.043750   0.908500
std     0.406381   0.045767   0.061198   0.071992
min    -0.771300   0.000000   0.000000   0.739000
25%    -0.231275   0.000000   0.000000   0.861500
50%     0.000000   0.051500   0.000000   0.918000
75%     0.345300   0.075750   0.071000   0.952500
max     0.636900   0.152000   0.187000   1.000000

In [49]:
# Describe the Ethereum Sentiment
# YOUR CODE HERE!
eth_df.describe()

        compound   positive  negative   neutral
count  20.000000  20.000000  20.00000  20.00000
mean    0.190925   0.078750   0.02975   0.89145
std     0.401422   0.085383   0.04006   0.10092
min    -0.526700   0.000000   0.00000   0.69200
25%     0.000000   0.000000   0.00000   0.84100
50%     0.025800   0.066500   0.00000   0.91050
75%     0.514625   0.120500   0.06125   1.00000
max     0.834000   0.249000   0.11500   1.00000

### Questions:

Q: Which coin had the highest mean positive score?

A: Ethereum

Q: Which coin had the highest compound score?

A: Ethereum

Q. Which coin had the highest positive score?

A: Ethereum

---

## 2. Natural Language Processing
---
###   Tokenizer

In this section, you will use NLTK and Python to tokenize the text for each coin. Be sure to:
1. Lowercase each word.
2. Remove Punctuation.
3. Remove Stopwords.

In [50]:
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from string import punctuation
import re

In [51]:
# Instantiate the lemmatizer
# YOUR CODE HERE!
lem = WordNetLemmatizer()
# Create a list of stopwords
stop_words = set(stopwords.words('english'))
# YOUR CODE HERE!

# Expand the default stopwords list if necessary
# YOUR CODE HERE!

In [56]:
# Complete the tokenizer function
def tokenizer(text):
    """Tokenizes text."""
    
    # Remove the punctuation from text
    print(text)
    res = re.sub(r'[^\w\s]', '', text)

   
    # Create a tokenized list of the words
    words = word_tokenize(text)
    
    
    # Lemmatize words into root words
    words_lem = lem.lemmatize(words)

   
    # Convert the words to lowercase
    words_lem = [i.lower() for i in words_lem]
    
    # Remove the stop words
    tokens = [i for i in words_lem if i not in stop_words]
    
    
    return tokens

In [57]:
# Create a new tokens columne for Bitcoin
tokenizer(articles_btc['articles'][0])
# tokens = 
# YOUR CODE HERE!

{'source': {'id': 'the-verge', 'name': 'The Verge'}, 'author': 'Elizabeth Lopatto', 'title': 'If you’re a Russian YouTuber, how do you get paid now?', 'description': 'Russian creators are shut off from the global financial system. Some of them are turning to cryptocurrency.', 'url': 'https://www.theverge.com/2022/3/17/22982122/russia-youtube-crypto-creators-pay-ruble', 'urlToImage': 'https://cdn.vox-cdn.com/thumbor/MG_NhB7wSIBIl3S_LG-y-r7iPmg=/0x215:3000x1786/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/9442221/cryptocurrency_0004__00000_.jpg', 'publishedAt': '2022-03-17T13:33:43Z', 'content': 'When Russia invaded Ukraine, Niki Proshin was already a year into making a living as a vlogger — he had a YouTube channel, a TikTok channel, and an Instagram. He also ran an online Russian club for a… [+5883 chars]'}

TypeError: expected string or bytes-like object

In [14]:
# Create a new tokens column for Ethereum
# YOUR CODE HERE!

---

### NGrams and Frequency Analysis

In this section you will look at the ngrams and word frequency for each coin. 

1. Use NLTK to produce the n-grams for N = 2. 
2. List the top 10 words for each coin.

In [15]:
from collections import Counter
from nltk import ngrams

In [16]:
# Generate the Bitcoin N-grams where N=2
# YOUR CODE HERE!

In [17]:
# Generate the Ethereum N-grams where N=2
# YOUR CODE HERE!

In [18]:
# Function token_count generates the top 10 words for a given coin
def token_count(tokens, N=3):
    """Returns the top N tokens from the frequency count"""
    return Counter(tokens).most_common(N)

In [19]:
# Use token_count to get the top 10 words for Bitcoin
# YOUR CODE HERE!

In [20]:
# Use token_count to get the top 10 words for Ethereum
# YOUR CODE HERE!

---

### Word Clouds

In this section, you will generate word clouds for each coin to summarize the news for each coin

In [21]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [20.0, 10.0]

In [22]:
# Generate the Bitcoin word cloud
# YOUR CODE HERE!

In [23]:
# Generate the Ethereum word cloud
# YOUR CODE HERE!

---
## 3. Named Entity Recognition

In this section, you will build a named entity recognition model for both Bitcoin and Ethereum, then visualize the tags using SpaCy.

In [24]:
import spacy
from spacy import displacy

In [25]:
# Download the language model for SpaCy
# !python -m spacy download en_core_web_sm

In [26]:
# Load the spaCy model
nlp = spacy.load('en_core_web_sm')

---
### Bitcoin NER

In [27]:
# Concatenate all of the Bitcoin text together
# YOUR CODE HERE!

In [28]:
# Run the NER processor on all of the text
# YOUR CODE HERE!

# Add a title to the document
# YOUR CODE HERE!

In [29]:
# Render the visualization
# YOUR CODE HERE!

In [30]:
# List all Entities
# YOUR CODE HERE!

---

### Ethereum NER

In [31]:
# Concatenate all of the Ethereum text together
# YOUR CODE HERE!

In [32]:
# Run the NER processor on all of the text
# YOUR CODE HERE!

# Add a title to the document
# YOUR CODE HERE!

In [33]:
# Render the visualization
# YOUR CODE HERE!

In [34]:
# List all Entities
# YOUR CODE HERE!

---